on: workflow_dispatch

name: Create city map

jobs:
  update:
    name: Create city map
    runs-on: macos-latest
    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1

      # Install required packages and update README
      - name: Install required packages
        run: |
          install.packages(c("remotes", "ggplot2", "dplyr", "tweenr"))
        shell: Rscript {0}

      - name: Install mathart package
        run: |
          remotes::install_github("marcusvolz/mathart")
        shell: Rscript {0}

      - name: Create city painting
        run: |
          source("city-maps/citypainting.R")
        shell: Rscript {0}

      # Create a pull request with changes to master
      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: New city map
          signoff: false
          branch: city-map
          delete-branch: true
          title: 'New city map'
          body: |
            New city painting: [1]

            - hello
          labels: |
            automated pr
          draft: false

      # Check outputs of workflow
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"