on: workflow_dispatch

name: Create city map

jobs:
  update:
    name: Create city map
    runs-on: windows-latest
    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1

      # Install required packages and update README
      - name: Install required packages and render script
        run: |
          install.packages(c("remotes", "rmarkdown", "gifski", "ggplot2", "dplyr", "tweenr"))
        shell: Rscript {0}

      - name: Install mathart
        run: |
          remotes::install_github("marcusvolz/mathart")
        shell: Rscript {0}

      - name: Render script
        run: |
          rmarkdown::render("city-maps/citypainting.Rmd")
        shell: Rscript {0}

      # Make sure only the images and data set are committed
      - name: Remove city-maps/citypainting.html
        run: |
          git add .
          git rm -f city-maps/citypainting.html

      # Create a pull request with changes to master
      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update package statistics
          signoff: false
          branch: city-map
          delete-branch: true
          title: 'New city map'
          body: |
            Daily update
          labels: |
            automated pr
          reviewers: koenderks
          draft: false

      # Check outputs of workflow
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"