on:
  schedule:
    - cron:  '00 00 * * *'

name: Create new painting

jobs:
  update:
    name: Create new painting
    runs-on: macos-latest
    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1

      # Install required packages and update README
      - name: Install required packages
        run: |
          install.packages(c("remotes", "randomcoloR"))
          remotes::install_github("koenderks/aRtsy")
        shell: Rscript {0}

      - name: Create new painting
        run: |
          source(".github/workflows/generate_painting.R")
        shell: Rscript {0}

      # Create a pull request with changes to master
      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: New painting
          signoff: false
          branch: new-painting
          delete-branch: true
          title: 'New painting'
          body: |
            Today's painting:

            ![image](https://github.com/koenderks/aRtsy/raw/new-painting/png/daily.png)
          draft: false

      # Check outputs of workflow
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"